#!/usr/bin/env bash
# Downloads libheif's fuzzing corpus (files that crashed or stressed libheif) into
# fuzz/seeds/libheif/, used as extra seeds by scripts/fuzz.sh. Files are not committed.
set -euo pipefail
cd "$(dirname "$0")/../fuzz"
mkdir -p seeds/libheif
BASE=https://raw.githubusercontent.com/strukturag/libheif/bb5e04a1c93d5e421e0936374fc11e01930f6768
while read -r path; do
  out="seeds/libheif/$(basename "$path")"
  [ -f "$out" ] || curl -fsSL "$BASE/$path" -o "$out"
done <<EOF
fuzzing/data/corpus/av1-huge-frame-header-oom.heic
fuzzing/data/corpus/avc32.heif
fuzzing/data/corpus/avif32-mini.heif
fuzzing/data/corpus/avif32.heif
fuzzing/data/corpus/clap-overflow-divide-zero.heic
fuzzing/data/corpus/clusterfuzz-testcase-minimized-file-fuzzer-4616081830051840.heic
fuzzing/data/corpus/clusterfuzz-testcase-minimized-file-fuzzer-5120279175102464.heic
fuzzing/data/corpus/clusterfuzz-testcase-minimized-file-fuzzer-5643900194127872.heic
fuzzing/data/corpus/clusterfuzz-testcase-minimized-file-fuzzer-5651556035198976.heic
fuzzing/data/corpus/clusterfuzz-testcase-minimized-file-fuzzer-5662360964956160.heic
fuzzing/data/corpus/clusterfuzz-testcase-minimized-file-fuzzer-5671864958976000.heic
fuzzing/data/corpus/clusterfuzz-testcase-minimized-file-fuzzer-5686319331672064.heic
fuzzing/data/corpus/clusterfuzz-testcase-minimized-file-fuzzer-5718632116518912.heic
fuzzing/data/corpus/clusterfuzz-testcase-minimized-file-fuzzer-5720856641142784.heic
fuzzing/data/corpus/clusterfuzz-testcase-minimized-file-fuzzer-5724458239655936.heic
fuzzing/data/corpus/clusterfuzz-testcase-minimized-file-fuzzer-5732616832024576.heic
fuzzing/data/corpus/clusterfuzz-testcase-minimized-file-fuzzer-5752063708495872.heic
fuzzing/data/corpus/clusterfuzz-testcase-minimized-file-fuzzer-5757633845264384.heic
fuzzing/data/corpus/clusterfuzz-testcase-minimized-file-fuzzer-6045213633282048.heic
fuzzing/data/corpus/colors-no-alpha-thumbnail.heic
fuzzing/data/corpus/colors-no-alpha.heic
fuzzing/data/corpus/colors-with-alpha-thumbnail.heic
fuzzing/data/corpus/colors-with-alpha.heic
fuzzing/data/corpus/crash-20ca2625096a205937b809a7841e7f019f0b2dc6.heic
fuzzing/data/corpus/github_138.heic
fuzzing/data/corpus/github_15.heic
fuzzing/data/corpus/github_20.heic
fuzzing/data/corpus/github_367_1.heic
fuzzing/data/corpus/github_367_2.heic
fuzzing/data/corpus/github_44.heic
fuzzing/data/corpus/github_45.heic
fuzzing/data/corpus/github_46_1.heic
fuzzing/data/corpus/github_46_2.heic
fuzzing/data/corpus/github_47.heic
fuzzing/data/corpus/github_48.heic
fuzzing/data/corpus/github_49.heic
fuzzing/data/corpus/github_50.heic
fuzzing/data/corpus/hbo_heif_context.h_126_1.heic
fuzzing/data/corpus/hevc32-mini.heif
fuzzing/data/corpus/hevc32.heif
fuzzing/data/corpus/j2k-siz-segment-undersized.heic
fuzzing/data/corpus/j2k32.heif
fuzzing/data/corpus/j2kH-sdtp-dump-timeout.heic
fuzzing/data/corpus/jpeg32.heif
fuzzing/data/corpus/region-mask-missing-refs.heic
fuzzing/data/corpus/rgb_generic_compressed_brotli.heic
fuzzing/data/corpus/rgb_generic_compressed_defl.heic
fuzzing/data/corpus/rgb_generic_compressed_tile_deflate.heic
fuzzing/data/corpus/rgb_generic_compressed_zlib.heic
fuzzing/data/corpus/rgb_generic_compressed_zlib_rows.heic
fuzzing/data/corpus/rgb_generic_compressed_zlib_tiled.heic
fuzzing/data/corpus/uaf_heif_context.h_117_1.heic
fuzzing/data/corpus/unci-pixel-interleave-wide-tile-timeout.heic
fuzzing/data/corpus/unci32.heif
fuzzing/data/corpus/uncompressed_comp_ABGR.heic
fuzzing/data/corpus/uncompressed_comp_ABGR_tiled.heic
fuzzing/data/corpus/uncompressed_comp_B16R16G16.heic
fuzzing/data/corpus/uncompressed_comp_B16R16G16_tiled.heic
fuzzing/data/corpus/uncompressed_comp_M.heic
fuzzing/data/corpus/uncompressed_comp_M_tiled.heic
fuzzing/data/corpus/uncompressed_comp_R5G6B5_tiled.heic
fuzzing/data/corpus/uncompressed_comp_R7+1G7+1B7+1_tiled.heic
fuzzing/data/corpus/uncompressed_comp_R7G7+1B7_tiled.heic
fuzzing/data/corpus/uncompressed_comp_R7G7B7_tiled.heic
fuzzing/data/corpus/uncompressed_comp_RGB.heic
fuzzing/data/corpus/uncompressed_comp_RGB_tiled.heic
fuzzing/data/corpus/uncompressed_comp_RGB_tiled_row_tile_align.heic
fuzzing/data/corpus/uncompressed_comp_RGxB.heic
fuzzing/data/corpus/uncompressed_comp_RGxB_tiled.heic
fuzzing/data/corpus/uncompressed_comp_VUY_420.heic
fuzzing/data/corpus/uncompressed_comp_VUY_422.heic
fuzzing/data/corpus/uncompressed_comp_Y16U16V16_420.heic
fuzzing/data/corpus/uncompressed_comp_Y16U16V16_422.heic
fuzzing/data/corpus/uncompressed_comp_YUV_420.heic
fuzzing/data/corpus/uncompressed_comp_YUV_422.heic
fuzzing/data/corpus/uncompressed_comp_YUV_tiled.heic
fuzzing/data/corpus/uncompressed_comp_YVU_420.heic
fuzzing/data/corpus/uncompressed_comp_YVU_422.heic
fuzzing/data/corpus/uncompressed_mix_VUY_420.heic
fuzzing/data/corpus/uncompressed_mix_VUY_422.heic
fuzzing/data/corpus/uncompressed_mix_Y16U16V16_420.heic
fuzzing/data/corpus/uncompressed_mix_Y16U16V16_422.heic
fuzzing/data/corpus/uncompressed_mix_YUV_420.heic
fuzzing/data/corpus/uncompressed_mix_YUV_422.heic
fuzzing/data/corpus/uncompressed_mix_YVU_420.heic
fuzzing/data/corpus/uncompressed_mix_YVU_422.heic
fuzzing/data/corpus/uncompressed_pix_ABGR.heic
fuzzing/data/corpus/uncompressed_pix_ABGR_tiled.heic
fuzzing/data/corpus/uncompressed_pix_B16R16G16.heic
fuzzing/data/corpus/uncompressed_pix_B16R16G16_tiled.heic
fuzzing/data/corpus/uncompressed_pix_M.heic
fuzzing/data/corpus/uncompressed_pix_M_tiled.heic
fuzzing/data/corpus/uncompressed_pix_R5G6B5_tiled.heic
fuzzing/data/corpus/uncompressed_pix_R7+1G7+1B7+1_tiled.heic
fuzzing/data/corpus/uncompressed_pix_R7G7+1B7_tiled.heic
fuzzing/data/corpus/uncompressed_pix_R7G7B7_tiled.heic
fuzzing/data/corpus/uncompressed_pix_R8G8B8A8_bsz0_psz10_tiled.heic
fuzzing/data/corpus/uncompressed_pix_R8G8B8A8_bsz0_psz5_tiled.heic
fuzzing/data/corpus/uncompressed_pix_R8G8B8_bsz0_psz10_tiled.heic
fuzzing/data/corpus/uncompressed_pix_R8G8B8_bsz0_psz5_tiled.heic
fuzzing/data/corpus/uncompressed_pix_RGB.heic
fuzzing/data/corpus/uncompressed_pix_RGB_tiled.heic
fuzzing/data/corpus/uncompressed_pix_RGB_tiled_row_tile_align.heic
fuzzing/data/corpus/uncompressed_pix_RGxB.heic
fuzzing/data/corpus/uncompressed_pix_RGxB_tiled.heic
fuzzing/data/corpus/uncompressed_pix_YUV_tiled.heic
fuzzing/data/corpus/uncompressed_row_ABGR.heic
fuzzing/data/corpus/uncompressed_row_ABGR_tiled.heic
fuzzing/data/corpus/uncompressed_row_B16R16G16.heic
fuzzing/data/corpus/uncompressed_row_B16R16G16_tiled.heic
fuzzing/data/corpus/uncompressed_row_M.heic
fuzzing/data/corpus/uncompressed_row_M_tiled.heic
fuzzing/data/corpus/uncompressed_row_R5G6B5_tiled.heic
fuzzing/data/corpus/uncompressed_row_R7+1G7+1B7+1_tiled.heic
fuzzing/data/corpus/uncompressed_row_R7G7+1B7_tiled.heic
fuzzing/data/corpus/uncompressed_row_R7G7B7_tiled.heic
fuzzing/data/corpus/uncompressed_row_RGB.heic
fuzzing/data/corpus/uncompressed_row_RGB_tiled.heic
fuzzing/data/corpus/uncompressed_row_RGB_tiled_row_tile_align.heic
fuzzing/data/corpus/uncompressed_row_RGxB.heic
fuzzing/data/corpus/uncompressed_row_RGxB_tiled.heic
fuzzing/data/corpus/uncompressed_row_YUV_tiled.heic
fuzzing/data/corpus/uncompressed_tile_ABGR_tiled.heic
fuzzing/data/corpus/uncompressed_tile_B16R16G16_tiled.heic
fuzzing/data/corpus/uncompressed_tile_M_tiled.heic
fuzzing/data/corpus/uncompressed_tile_R5G6B5_tiled.heic
fuzzing/data/corpus/uncompressed_tile_R7+1G7+1B7+1_tiled.heic
fuzzing/data/corpus/uncompressed_tile_R7G7+1B7_tiled.heic
fuzzing/data/corpus/uncompressed_tile_R7G7B7_tiled.heic
fuzzing/data/corpus/uncompressed_tile_RGB_tiled.heic
fuzzing/data/corpus/uncompressed_tile_RGB_tiled_row_tile_align.heic
fuzzing/data/corpus/uncompressed_tile_RGxB_tiled.heic
fuzzing/data/corpus/uncompressed_tile_YUV_tiled.heic
fuzzing/data/corpus/vvc32.heif
EOF
echo "ok: $(ls seeds/libheif | wc -l) files"
